### ISSUE TITLE
No issue for MicroPay , Need help for ExoPlayer extension

### ISSUE THREAD

**Issue by shan-mustafa** [Crossady/MicroPay#1]
I know this is not an appropriate way but i am looking way to communicate with you , i just come to you know that you have idea how to add ffmpeg and VP9 extension to project on Windows. 
My problem was that i have a video file that does lot of buffering with no sound. when i converted that file to MP4 it started playing fine with sound. after some research i come to know that i need to add ffmpeg and VP9 extension to play my file smoothly without converting it to MP4 first.
I've read below documentation....
https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg
https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9

and these doc don't make sense and i think the method mentioned here is not for Windows. So if you could please answer how i can setup my project with these extensions to play the file without conversion that may help  . I did some research and added Environmental Variables in Windows System Properties but that didn't work out and solve the decoding issue. May be i am missing something..
So if you know you how to add these decoder extensions and what code do i need to change in my project which apparently seems just to add a flag in DefaultRenderersFactory then it shall be very generous of you. Please....
I posted this question to ExoPlayer repository but they gave me your reference. Please help me out.

**Comment by schwarzichet** [comment]
well that's OK. I do not mind this. I am very willing to help.
It's an old question so I am not quite sure about everything. After I type these words I will try again.( begin from installing android studio 😂）
Can you tell me more details about what have you done, what error message you got？
The more details the better. 
All I know is about how to compiling these extensions and very limited usage about these extensions.

**Comment by shan-mustafa** [comment]
Nice and thanks :) ...
I've integrated ExoPlayer in my project to play locally stored files. I followed Exoplayer documentation and everything is working great but i tried to play .mpg file with ac3 audio. I find no audio & 
the video doesn't play smoothly - it appears to be buffering . though when i tested the same file to play on MX player or Android Media Player both the player played the file perfectly . Then i did some research and found out that i need to add decoders to Exoplayer which are actually Exoplayer's extensions ffmpeg for audio decoding and VP9 for video decoding then my file will start playing smoothly with perfect audio just like it played on MX or Android media player.
Based on my decoding research i converted my .mpg file to .mp4 with same resolution and it did play smoothly with perfect audio on Exoplayer . So i need add these extensions (ffmpeg and VP9) to my exoplayer project to make it play smoothly without convert it to mp4 first and i don't know how to add these extensions with my project. The documentation doesn't make sense...
So it shall be so nice of you if you could mention the steps to add these extensions with my project and i am using Windows here.

**Comment by schwarzichet** [comment]
so did you follow the Build instructions and successfully build two extensions?

**Comment by shan-mustafa** [comment]
I tried but build instructions are not for Windows but i downloaded the ExoPlayer repository "cd" to exoplayer folder and try to run this command on CMD/Powershell:
FFMPEG_EXT_PATH="E:\ExoPlayer-release-v2/extensions/ffmpeg/src/main/jni"  
but it didn't work out and give me an error.
Did i miss something or if my understanding not correct then you can correct me please.

**Comment by schwarzichet** [comment]
For powershell you should set environment variable in this way:
`$Env:FFMPEG_EXT_PATH = "E:\ExoPlayer-release-v2\extensions\ffmpeg\src\main\jni"`
Also same for next procedures like set Android NDK enviroment variables.
Try to follow the next steps then we will see what's next question.

**Comment by shan-mustafa** [comment]
Perfect, Great !!  postfixed the command with $Env: gives no error.
Done with FFMPEG_EXT_PATH & NDK_PATH
Now what to replace here with HOST_PLATFORM? : 
HOST_PLATFORM="linux-x86_64"

**Comment by schwarzichet** [comment]
follow the instructions in 
[https://developer.android.com/ndk/guides/other_build_systems](url)

> 

NDK OS Variant | Host Tag
-- | --
macOS | darwin-x86_64
Linux | linux-x86_64
32-bit Windows | windows
64-bit Windows | windows-x86_64

**Comment by shan-mustafa** [comment]
Thanks for bearing with me really appreciate that.
Now please tell me how to Fetch and build FFmpeg.

**Comment by schwarzichet** [comment]
Basically I guess it's same as what are described in instructions 
While you can do the commands step by step.
 Similarly you should set environment variables "COMMON_OPTIONS" in Powershell way.
before you do 
`./configure \
    --libdir=android-libs/armeabi-v7a \
    --arch=arm \
    --cpu=armv7-a \
    --cross-prefix="${NDK_PATH}/toolchains/arm-linux-androideabi-4.9/prebuilt/${HOST_PLATFORM}/bin/arm-linux-androideabi-" \
    --sysroot="${NDK_PATH}/platforms/android-9/arch-arm/" \
    --extra-cflags="-march=armv7-a -mfloat-abi=softfp" \
    --extra-ldflags="-Wl,--fix-cortex-a8" \
    --extra-ldexeflags=-pie \
    ${COMMON_OPTIONS} \`
you should follow the instructions in https://developer.android.com/ndk/guides/other_build_systems
In "Autoconf" or "Non-Autoconf make projects", set some environment variables like what compiler you should use, where is your "make" command before you do the cross compiling.
While it says autoconf not work in windows. So I am not sure what to do here. Maybe you need to try it yourself
I never use FFmpeg extension so I cannot give you more help here. 
Well, if that not work, I suggest you use Linux for Android develop.

**Comment by shan-mustafa** [comment]
Thanks for the guide brother, really appreciate that :)

**Comment by schwarzichet** [comment]
you are welcome
